version: '3'
services:
  #js-app:
    #image: 734066168422.dkr.ecr.us-east-2.amazonaws.com/js-app:1.0
    #ports:
      #- 3000:3000
    #environment:
     # - MONGO_DB_USERNAME=admin
      #- MONGO_DB_PWD=admin


  mongodb:
    image: mongo:4.4
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - "mongodb"

volumes:
  mongo-data:
    driver: local

